<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["clientes/index", "Regresar"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["clientes/new", "Agregar nueva informacion de cliente"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Resultados de la busqueda</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Nombre</th>
            <th>Emailid</th>
            <th>Aporte</th>
            <th>Mes</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $cliente): ?>
            <tr>
                <td><?php echo $cliente->id ?></td>
            <td><?php echo $cliente->name ?></td>
            <td><?php echo $cliente->emailid ?></td>
            <td><?php echo $cliente->aporte ?></td>
            <td><?php echo $cliente->mes ?></td>

                <td><?php echo $this->tag->linkTo(["clientes/edit/" . $cliente->id, "Editar"]); ?></td>
                <td><?php echo $this->tag->linkTo(["clientes/delete/" . $cliente->id, "Eliminar"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["clientes/search", "Primera pagina", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["clientes/search?page=" . $page->before, "Pagina anterior", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["clientes/search?page=" . $page->next, "Pagina siguiente", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["clientes/search?page=" . $page->last, "Ultima pagina", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
